### ISSUE TITLE
წვიმა

### ISSUE THREAD

**Issue by TMandzu** [freeuni-sdp/iot-weather#1]
"იცის სახლის მდებარეობა. ამ მდებარეობისათვის მოიპოვებს ამინდის მონაცემებს მესამე სერვისისგან. შეუძლია გასცეს პაუსხი კითხვას იწვიმებს თუ არა შემდეგ 24 საათში. წვიმის ალბათობის threshold-იც ამ სერვისის ცოდნის ნაწილია. აგრეთვე შესაძლებელია აქტუალური გარე ტემპერატურის წაკითხვა." - აქ მეორე რაც წერია ეგ ნიშნავს, რომ გვაინტერესებს რა ალბათობით იწვიმებს შემდეგი 24 საათის განმავლობაში?

**Comment by gkiko** [comment]
შენმა სერვისმა უნდა დააბრუნოს 'კი' ან 'არა' თუ მაგალითად მომავალ 1 საათში
იწვიმებს

**Comment by TMandzu** [comment]
აა, ანუ 1-დან 24-მდე ყველა საათისთვის უნდა შეეძლოს პასუხის გაცემა იწვიმებს თუ არა? 
და "ალბათობის threshold" რატოა ნახსენები? წვიმის მოსვლის ალბათობა არ გვჭირდება?

**Comment by gkiko** [comment]
შემეშალა. გპასუხობს მომავალი 24 საათის განმავლობაში თუ იწვიმებს. _threshold_-უნდა გამოიყოენოს, რომ ამინდის პროგნოზიდან მოსული 60%-ანი წვიმა 'კი'-ში ჩათვალოს თუ 'არა'-ში

**Comment by TMandzu** [comment]
გასაგებია, მადლობა
