### ISSUE TITLE
სახლის კოორდინატები

### ISSUE THREAD

**Issue by TMandzu** [freeuni-sdp/iot-weather#2]
"გაითვალისწინეთ, სისტემაში ჩართული იქნება ერთზე მეტი სახლი!"
"იცის სახლის მდებარეობა. ამ მდებარეობისათვის მოიპოვებს ამინდის მონაცემებს მესამე სერვისისგან."

ესენი წერია პირობაში. კოდში წინასწარ უნდა გავწერო კოორდინატები, გაშვებისას იყოს არგუმენტების სახით თუ მომხმარებელს მივცე უფლება ჰტმლ რექვესთით შეცვალოს ან დააყენოს? თუ როგორც მინდა?

**Comment by gkiko** [comment]
დასაწერი იქნება ახალი სერვისი, რომლიდანაც წამოიღებ სახლის ინფორმაციას. შენ გადმოგცემენ სახლის id-ს, შენ კი ამ სერვისს კითხავ საჭირო ინფორმაციას

**Comment by TMandzu** [comment]
მადლობა
